name: CI_Preprod_Groupe6

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
  schedule:
    - cron: "0 3,11,19 * * *"

env:
  MANAGER1_EMAIL: ${{ secrets.MANAGER1_EMAIL }}
  MONITOR1_EMAIL: ${{ secrets.MONITOR1_EMAIL }}
  TEACHER1_EMAIL: ${{ secrets.TEACHER1_EMAIL }}
  ADMIN1_EMAIL: ${{ secrets.ADMIN1_EMAIL }}
  STUDENT1_EMAIL: ${{ secrets.STUDENT1_EMAIL }}

  REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
  REACT_APP_AWS_REGION: eu-west-3
  STUDENT1_PASSWORD: ${{ secrets.STUDENT1_PASSWORD }}
  TEACHER1_PASSWORD: ${{ secrets.TEACHER1_PASSWORD }}
  MANAGER1_PASSWORD: ${{ secrets.MANAGER1_PASSWORD }}
  MONITOR1_PASSWORD: ${{ secrets.MONITOR1_PASSWORD }}
  REACT_APP_USERPOOL_ID: ${{ vars.PREPROD_USERPOOL_ID }}
  REACT_APP_WEBCLIENT_ID: ${{ vars.PREPROD_WEBCLIENT_ID }}
  REACT_APP_OAUTH_DOMAIN: ${{ vars.PREPROD_OAUTH_DOMAIN }}
  WAF_JS_API_URL: ${{ secrets.WAF_JS_API_URL }}
  WAF_INTEGRATION_API_KEY: ${{ secrets.WAF_INTEGRATION_API_KEY }}
  REACT_APP_CASDOOR_SDK_SERVER_URL: ${{ secrets.REACT_APP_CASDOOR_SDK_SERVER_URL }}
  REACT_APP_CASDOOR_SDK_CLIENT_ID: ${{ secrets.REACT_APP_CASDOOR_SDK_CLIENT_ID }}
  REACT_APP_CASDOOR_SDK_APP_NAME: ${{ secrets.REACT_APP_CASDOOR_SDK_APP_NAME }}
  REACT_APP_CASDOOR_SDK_ORGANIZATION_NAME: ${{ secrets.REACT_APP_CASDOOR_SDK_ORGANIZATION_NAME }}
  REACT_APP_CASDOOR_SDK_REDIRECT_PATH: ${{ secrets.REACT_APP_CASDOOR_SDK_REDIRECT_PATH }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.19.0

      - name: Supprimer .npmrc global (si présent)
        run: rm -f ~/.npmrc

      - name: Supprimer .npmrc local (si présent)
        run: rm -f .npmrc

      - name: Configure AWS credentials (prod)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REACT_APP_AWS_REGION }}

      - run: sh ./initNpmrc.sh hei-store npm-hei-school 088312068315

      - name: Configure AWS credentials (preprod)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.PREPROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PREPROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REACT_APP_AWS_REGION }}
          unset-current-credentials: true

      - run: sh ./initNpmrc.sh hei-store npm-hei-lab 057045785189

      - run: npm ci
      - run: npm run format:check

  test-e2e:
    timeout-minutes: 35
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18.19.0

      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Supprimer .npmrc global (si présent)
        run: rm -f ~/.npmrc

      - name: Supprimer .npmrc local (si présent)
        run: rm -f .npmrc

      - name: Configurer AWS + npmrc (prod puis preprod)
        run: |
          aws configure set aws_access_key_id ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ env.REACT_APP_AWS_REGION }}
          sh ./initNpmrc.sh hei-store npm-hei-school 088312068315
          aws configure set aws_access_key_id ${{ secrets.PREPROD_AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.PREPROD_AWS_SECRET_ACCESS_KEY }}
          sh ./initNpmrc.sh hei-store npm-hei-lab 057045785189

      - run: npm install --location=global sonar-scanner

      - run: npm install --save-dev ts-node typescript

      - name: Read version
        id: read-version
        uses: CumulusDS/get-yaml-paths-action@v0.1.0
        with:
          file: version.yml
          version: version

      - name: Run Cypress tests on preprod
        env:
          CYPRESS_BASE_URL: https://preprod.admin.hei.school
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --e2e --env codeCoverage=true

      - name: Merge reports + Sonar
        if: always()
        run: |
          npx nyc report --reporter=lcov
          npm run test:merge:reports
          sonar-scanner \
            -Dsonar.projectVersion=${{ steps.read-version.outputs.version }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.organization=hei-school \
            -Dsonar.projectKey=hei_admin-ui \
            -Dsonar.branch.name=${{ github.ref_name }} \
            -Dsonar.host.url=https://sonarcloud.io

      - name: Instatus update (UP)
        env:
          INSTATUS_PAYMENT_WEBHOOK: ${{ secrets.INSTATUS_PAYMENT_WEBHOOK }}
          INSTATUS_AUTH_WEBHOOK: ${{ secrets.INSTATUS_AUTH_WEBHOOK }}
          INSTATUS_PRESENCE_WEBHOOK: ${{ secrets.INSTATUS_PRESENCE_WEBHOOK }}
          INSTATUS_ETUDIANT_WEBHOOK: ${{ secrets.INSTATUS_ETUDIANT_WEBHOOK }}
        run: |
          curl -X POST $INSTATUS_PAYMENT_WEBHOOK \
          -H 'Content-Type: application/json' \
          -d '{"trigger": "incident", "status": "resolved", "message": "Payment back up from GitHub CI"}'

          curl -X POST $INSTATUS_AUTH_WEBHOOK \
          -H 'Content-Type: application/json' \
          -d '{"trigger": "incident", "status": "resolved", "message": "Auth back up from GitHub CI"}'

          curl -X POST $INSTATUS_PRESENCE_WEBHOOK \
          -H 'Content-Type: application/json' \
          -d '{"trigger": "incident", "status": "resolved", "message": "Presence back up from GitHub CI"}'

          curl -X POST $INSTATUS_ETUDIANT_WEBHOOK \
          -H 'Content-Type: application/json' \
          -d '{"trigger": "incident", "status": "resolved", "message": "Etudiant back up from GitHub CI"}'

      - name: Instatus update (DOWN if failure)
        if: failure()
        env:
          INSTATUS_PAYMENT_WEBHOOK: ${{ secrets.INSTATUS_PAYMENT_WEBHOOK }}
          INSTATUS_AUTH_WEBHOOK: ${{ secrets.INSTATUS_AUTH_WEBHOOK }}
          INSTATUS_PRESENCE_WEBHOOK: ${{ secrets.INSTATUS_PRESENCE_WEBHOOK }}
          INSTATUS_ETUDIANT_WEBHOOK: ${{ secrets.INSTATUS_ETUDIANT_WEBHOOK }}
        run: |
          curl -X POST $INSTATUS_PAYMENT_WEBHOOK \
          -H 'Content-Type: application/json' \
          -d '{"trigger": "incident", "status": "investigating", "message": "Payment failed in GitHub CI"}'

          curl -X POST $INSTATUS_AUTH_WEBHOOK \
          -H 'Content-Type: application/json' \
          -d '{"trigger": "incident", "status": "investigating", "message": "Auth failed in GitHub CI"}'

          curl -X POST $INSTATUS_PRESENCE_WEBHOOK \
          -H 'Content-Type: application/json' \
          -d '{"trigger": "incident", "status": "investigating", "message": "Presence failed in GitHub CI"}'

          curl -X POST $INSTATUS_ETUDIANT_WEBHOOK \
          -H 'Content-Type: application/json' \
          -d '{"trigger": "incident", "status": "investigating", "message": "Etudiant failed in GitHub CI"}'

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.19.0

      - name: AWS + Build
        run: |
          aws configure set aws_access_key_id ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ env.REACT_APP_AWS_REGION }}
          sh ./initNpmrc.sh hei-store npm-hei-school 088312068315
          aws configure set aws_access_key_id ${{ secrets.PREPROD_AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.PREPROD_AWS_SECRET_ACCESS_KEY }}
          sh ./initNpmrc.sh hei-store npm-hei-lab 057045785189

      - run: |
          npm ci
          npm run build

  cleanup-preprod-data:
    if: github.ref_name == 'CI-TEST'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Call cleanup endpoint
        run: |
          curl -X POST https://preprod.admin.hei.school/api/cleanup \
            -H "Authorization: Bearer ${{ secrets.PREPROD_CLEANUP_TOKEN }}" \
            -H "Content-Type: application/json"
